#!/usr/bin/env bash
# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# Cloud Native Stack Undeployment Script
# Generated by AICR Bundler v1.0.0
#
# Usage: ./undeploy.sh [--keep-namespaces] [--delete-pvcs] [--timeout SECONDS] [--skip-preflight]
#   --keep-namespaces   Skip deleting namespaces after uninstalling components
#   --delete-pvcs       Delete all PVCs in component namespaces (default: skip)
#   --timeout SECONDS   Timeout for helm uninstall and kubectl delete operations
#   --skip-preflight    Skip pre-flight finalizer checks (use with caution)
#
# This script is optional — components can be removed manually with helm uninstall.
# For detailed behavior docs (PVC preservation, namespace ordering, stuck release
# handling), see the AICR CLI Reference:
#   https://github.com/NVIDIA/aicr/blob/main/docs/user/cli-reference.md#undeploy-script-behavior-undeploysh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

KEEP_NS=false
DELETE_PVCS=false
SKIP_PREFLIGHT=false
HELM_TIMEOUT=120
while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep-namespaces) KEEP_NS=true; shift ;;
    --delete-pvcs) DELETE_PVCS=true; shift ;;
    --skip-preflight) SKIP_PREFLIGHT=true; shift ;;
    --timeout)
      if [[ $# -lt 2 ]]; then echo "Error: --timeout requires a value"; exit 1; fi
      HELM_TIMEOUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# jq is required for CRD/finalizer inspection and cleanup.
if ! command -v jq &>/dev/null; then
  echo "Error: jq is required but not found in PATH."
  echo "  Install jq: https://jqlang.github.io/jq/download/"
  exit 1
fi

echo "Undeploying Cloud Native Stack components (timeout: ${HELM_TIMEOUT}s)..."
echo ""

echo "  The following components will be removed (in reverse install order):"
# List NNN-* folders in reverse numeric order
for dir in $(ls -1d "${SCRIPT_DIR}"/[0-9][0-9][0-9]-*/ 2>/dev/null | sort -r); do
  [[ -d "${dir}" ]] || continue
  base="${dir%/}"
  base="${base##*/}"
  name="${base#[0-9][0-9][0-9]-}"
  printf "    %-40s\n" "${name}"
done
echo ""

# System namespaces that must not be deleted
PROTECTED_NS="kube-system kube-public kube-node-lease default"

delete_namespace() {
  local ns="$1"
  if [[ "${KEEP_NS}" == "true" ]]; then return; fi
  if echo " ${PROTECTED_NS} " | grep -q " ${ns} "; then return; fi
  if ! kubectl get namespace "${ns}" &>/dev/null; then return; fi
  echo "Deleting namespace ${ns}..."
  kubectl delete namespace "${ns}" --ignore-not-found --wait=false
}

# Uninstall a Helm release, handling stuck pending states from interrupted deploys.
# Try normal uninstall first; if it fails, retry with --no-hooks to force removal.
helm_force_uninstall() {
  local release="$1"
  local ns="$2"
  if helm uninstall "${release}" -n "${ns}" --timeout "${HELM_TIMEOUT}s" --ignore-not-found 2>/dev/null; then
    return
  fi
  echo "  Retrying ${release} removal with --no-hooks..."
  helm uninstall "${release}" -n "${ns}" --no-hooks --timeout "${HELM_TIMEOUT}s" --ignore-not-found || true
}

# Delete cluster-scoped resources owned by a Helm release.
# These survive namespace deletion and can block subsequent deployments:
# - Webhooks block pod creation when their backing service is gone
# - CRDs with "helm.sh/resource-policy: keep" are retained after chart removal
delete_release_cluster_resources() {
  local release="$1"
  local ns="$2"
  local selector="app.kubernetes.io/managed-by=Helm"
  for kind in mutatingwebhookconfigurations validatingwebhookconfigurations customresourcedefinitions; do
    kubectl get "${kind}" -l "${selector}" -o json 2>/dev/null \
      | jq -r --arg rel "${release}" --arg ns "${ns}" \
        '.items[] | select(.metadata.annotations["meta.helm.sh/release-name"]==$rel and .metadata.annotations["meta.helm.sh/release-namespace"]==$ns) | .metadata.name' 2>/dev/null \
      | while read -r name; do
          echo "Deleting ${kind}/${name}..."
          kubectl delete "${kind}" "${name}" --ignore-not-found --timeout="${HELM_TIMEOUT}s" || true
        done || echo "Warning: ${kind} cleanup pipeline for release ${release}/${ns} failed (kubectl get / jq error); leftovers will surface in post-flight" >&2
  done
}

# Delete webhooks whose backing service is in a specific namespace and no longer exists.
# Scoped to the given namespace to avoid touching unrelated platform webhooks.
# Operator-created webhooks (e.g., kai-scheduler admission) may not carry Helm labels,
# but once their service namespace is deleted, fail-closed webhooks block pod creation.
delete_orphaned_webhooks_for_ns() {
  local ns="$1"
  for kind in mutatingwebhookconfigurations validatingwebhookconfigurations; do
    { kubectl get "${kind}" -o json 2>/dev/null \
      | jq -r --arg ns "${ns}" \
        '.items[] | .metadata.name as $wh | .webhooks[] | select(.clientConfig.service != null and .clientConfig.service.namespace == $ns) | [$wh, .clientConfig.service.name] | @tsv' 2>/dev/null \
      | sort -u || true; } \
      | while IFS=$'\t' read -r wh_name svc_name; do
          # Delete when namespace is gone, terminating, or backing service is missing.
          # Skip on transient errors (auth, timeout, DNS) to avoid removing valid webhooks.
          local ns_output ns_phase svc_output
          ns_output=$(kubectl get ns "${ns}" 2>&1) || true
          if echo "${ns_output}" | grep -q "NotFound"; then
            echo "Deleting orphaned ${kind}/${wh_name} (namespace ${ns} not found)..."
            kubectl delete "${kind}" "${wh_name}" --ignore-not-found
            continue
          fi
          ns_phase=$(kubectl get ns "${ns}" -o jsonpath='{.status.phase}' 2>/dev/null) || true
          if [[ "${ns_phase}" == "Terminating" ]]; then
            echo "Deleting orphaned ${kind}/${wh_name} (namespace ${ns} terminating)..."
            kubectl delete "${kind}" "${wh_name}" --ignore-not-found
            continue
          fi
          svc_output=$(kubectl get svc "${svc_name}" -n "${ns}" 2>&1) || true
          if echo "${svc_output}" | grep -q "NotFound"; then
            echo "Deleting orphaned ${kind}/${wh_name} (service ${ns}/${svc_name} not found)..."
            kubectl delete "${kind}" "${wh_name}" --ignore-not-found
          fi
        done
  done
}

# Force-clear finalizers on all namespaced resources to unstick a Terminating namespace.
force_clear_namespace_finalizers() {
  local ns="$1"
  echo "Force-removing finalizers in namespace ${ns}..."
  local kinds
  kinds=$(kubectl api-resources --verbs=list --namespaced -o name 2>/dev/null) || {
    echo "Warning: failed to enumerate namespaced resource kinds in ${ns}; namespace may stay Terminating" >&2
    return
  }
  for kind in ${kinds}; do
    kubectl get "${kind}" -n "${ns}" -o json 2>/dev/null \
      | jq -r '.items[] | select(.metadata.finalizers // [] | length > 0) | .kind + "/" + .metadata.name' 2>/dev/null \
      | while read -r resource; do
          kubectl patch "${resource}" -n "${ns}" --type merge -p '{"metadata":{"finalizers":null}}' 2>/dev/null || true
        done || echo "Warning: finalizer-clear pipeline for ${kind} in ${ns} failed (kubectl get / jq error); namespace may stay Terminating" >&2
  done
}

# Return a small, explicit list of known crds/-installed CRDs whose
# finalizer-bearing custom resources must still be caught before the operator
# is removed. Keep this list intentionally tiny and exact: if a release is not
# listed here, pre-flight relies on chart-manifest and Helm-annotation discovery
# only instead of trying to infer ownership across the whole cluster.
extra_crds_for_release() {
  case "$1" in
    gpu-operator)
      printf '%s\n' \
        "clusterpolicies.nvidia.com" \
        "nvidiadrivers.nvidia.com" \
        "nodefeaturegroups.nfd.k8s-sigs.io" \
        "nodefeaturerules.nfd.k8s-sigs.io" \
        "nodefeatures.nfd.k8s-sigs.io"
      ;;
    kai-scheduler)
      printf '%s\n' \
        "bindrequests.scheduling.run.ai" \
        "configs.kai.scheduler" \
        "podgroups.scheduling.run.ai" \
        "queues.scheduling.run.ai" \
        "schedulingshards.kai.scheduler" \
        "topologies.kai.scheduler"
      ;;
    k8s-nim-operator)
      printf '%s\n' \
        "nemocustomizers.apps.nvidia.com" \
        "nemodatastores.apps.nvidia.com" \
        "nemoentitystores.apps.nvidia.com" \
        "nemoevaluators.apps.nvidia.com" \
        "nemoguardrails.apps.nvidia.com" \
        "nimbuilds.apps.nvidia.com" \
        "nimcaches.apps.nvidia.com" \
        "nimpipelines.apps.nvidia.com" \
        "nimservices.apps.nvidia.com"
      ;;
    kubeflow-trainer)
      printf '%s\n' \
        "clustertrainingruntimes.trainer.kubeflow.org" \
        "trainjobs.trainer.kubeflow.org" \
        "trainingruntimes.trainer.kubeflow.org" \
        "jobsets.jobset.x-k8s.io"
      ;;
    kube-prometheus-stack)
      printf '%s\n' \
        "alertmanagerconfigs.monitoring.coreos.com" \
        "alertmanagers.monitoring.coreos.com" \
        "podmonitors.monitoring.coreos.com" \
        "probes.monitoring.coreos.com" \
        "prometheusagents.monitoring.coreos.com" \
        "prometheuses.monitoring.coreos.com" \
        "prometheusrules.monitoring.coreos.com" \
        "scrapeconfigs.monitoring.coreos.com" \
        "servicemonitors.monitoring.coreos.com" \
        "thanosrulers.monitoring.coreos.com"
      ;;
    dynamo-platform)
      printf '%s\n' \
        "podcliques.grove.io" \
        "podcliquescalinggroups.grove.io" \
        "podcliquesets.grove.io" \
        "podgangs.scheduler.grove.io"
      ;;
    network-operator)
      # This explicit list matches the CRDs enabled by the bundled values:
      # nfd=false, sriovNetworkOperator=false, maintenance-operator disabled.
      # Intentionally exclude networkattachmentdefinitions.k8s.cni.cncf.io:
      # it is a broadly shared CRD, so surfacing or deleting it based only on
      # this release would create cross-cluster noise.
      printf '%s\n' \
        "nicclusterpolicies.mellanox.com" \
        "hostdevicenetworks.mellanox.com" \
        "ipoibnetworks.mellanox.com" \
        "macvlannetworks.mellanox.com"
      ;;
    *) ;;
  esac
}

# Skip pre-flight for releases whose bundle-managed custom resources are
# deleted from manifests before the controller is uninstalled.
skip_preflight_for_release() {
  case "$1" in
    nodewright-operator|kgateway) return 0 ;;
    *) return 1 ;;
  esac
}

# Run `kubectl ... -o json` while keeping stdout parseable for jq.
# Closes kubectl's stdin so a broken kubeconfig (missing user / expired creds)
# cannot leak its "Please enter Username:" prompt — kubectl writes the prompt
# to *stdout* before detecting non-TTY stdin, which would otherwise land in
# the captured value and resurface in WARNING messages (see issue #684).
capture_kubectl_json() {
  local out_var="$1"
  shift
  local stderr_file output kubectl_err=""

  if ! stderr_file=$(mktemp "${TMPDIR:-/tmp}/.aicr_kubectl_stderr_XXXXXX"); then
    printf -v "${out_var}" '%s' 'mktemp failed while capturing kubectl stderr'
    return 1
  fi

  if ! output=$(kubectl "$@" 2>"${stderr_file}" </dev/null); then
    kubectl_err=$(cat "${stderr_file}" 2>/dev/null || true)
    rm -f "${stderr_file}"
    printf -v "${out_var}" '%s' "${kubectl_err}"
    return 1
  fi

  if [[ -s "${stderr_file}" ]]; then
    cat "${stderr_file}" >&2 || true
  fi
  rm -f "${stderr_file}"
  printf -v "${out_var}" '%s' "${output}"
  return 0
}

check_crd_for_stuck_resources() {
  local crd_name="$1"
  local component="$2"
  local crd_json plural group scope resource stuck stuck_json kubectl_err
  local item_name item_namespace item_finalizers

  if ! capture_kubectl_json crd_json get crd "${crd_name}" -o json; then
    kubectl_err="${crd_json}"
    echo "" >&2
    echo "ERROR: Pre-flight could not inspect CRD '${crd_name}' (release ${component})." >&2
    echo "  kubectl output: ${kubectl_err}" >&2
    echo "  Failing closed: if this is a transient API/auth error the script" >&2
    echo "  may remove the operator before finalizers are reconciled." >&2
    echo "  Re-run after the API recovers, or use --skip-preflight to bypass." >&2
    return 1
  fi
  read -r plural group scope < <(echo "${crd_json}" | jq -r '[.spec.names.plural, .spec.group, .spec.scope] | @tsv' 2>/dev/null) || return 0
  [[ -z "${plural}" || "${plural}" == "null" ]] && return 0

  resource="${plural}.${group}"
  local jq_filter='[.metadata.finalizers // [] | .[] | select(startswith("kubernetes.io/") | not)]'
  stuck=""
  if [[ "${scope}" == "Namespaced" ]]; then
    if ! capture_kubectl_json stuck_json get "${resource}" -A -o json; then
      echo "" >&2
      echo "ERROR: Pre-flight could not list '${resource}' (release ${component})." >&2
      echo "  kubectl output: ${stuck_json}" >&2
      echo "  Failing closed so we do not silently miss a stuck CR." >&2
      echo "  Re-run after the API recovers, or use --skip-preflight to bypass." >&2
      return 1
    fi
    while IFS=$'\x1f' read -r item_namespace item_name item_finalizers; do
      stuck="${stuck}    ${item_namespace}/${item_name}  finalizers=[${item_finalizers}]"$'\n'
    done < <(echo "${stuck_json}" \
      | jq -r '.items[] | ('"${jq_filter}"') as $f | select(($f | length) > 0) | [(.metadata.namespace // ""), .metadata.name, ($f | join(","))] | join("")' 2>/dev/null || true)
  else
    if ! capture_kubectl_json stuck_json get "${resource}" -o json; then
      echo "" >&2
      echo "ERROR: Pre-flight could not list '${resource}' (release ${component})." >&2
      echo "  kubectl output: ${stuck_json}" >&2
      echo "  Failing closed so we do not silently miss a stuck CR." >&2
      echo "  Re-run after the API recovers, or use --skip-preflight to bypass." >&2
      return 1
    fi
    while IFS=$'\x1f' read -r item_name item_finalizers; do
      stuck="${stuck}    ${item_name}  finalizers=[${item_finalizers}]"$'\n'
    done < <(echo "${stuck_json}" \
      | jq -r '.items[] | ('"${jq_filter}"') as $f | select(($f | length) > 0) | [.metadata.name, ($f | join(","))] | join("")' 2>/dev/null || true)
  fi

  if [[ -n "${stuck}" ]]; then
    {
      echo "  ${component} — ${crd_name}:"
      printf '%s' "${stuck}"
    } >> "${PREFLIGHT_DETAILS}"
  fi
}

check_release_for_stuck_crds() {
  local release="$1"
  local ns="$2"
  local manifest manifest_crds annotated_crds explicit_crds
  local all_crds_json kubectl_err crd_name
  manifest=$(helm get manifest "${release}" -n "${ns}" 2>/dev/null || true)
  manifest_crds=$(echo "${manifest}" \
    | awk '/^kind:/{kind=$2} /^  name:/ && kind=="CustomResourceDefinition"{print $2; kind=""}')

  all_crds_json="${PREFLIGHT_ALL_CRDS_JSON:-}"
  if [[ -z "${all_crds_json}" ]]; then
    if ! capture_kubectl_json all_crds_json get crd -o json; then
      kubectl_err="${all_crds_json}"
      echo "" >&2
      echo "ERROR: Pre-flight could not list CRDs for release '${release}'." >&2
      echo "  kubectl output: ${kubectl_err}" >&2
      echo "  Failing closed: if this is a transient API/auth error the script" >&2
      echo "  may remove the operator before finalizers are reconciled." >&2
      echo "  Re-run after the API recovers, or use --skip-preflight to bypass." >&2
      return 1
    fi
  fi

  annotated_crds=$(echo "${all_crds_json}" \
    | jq -r --arg rel "${release}" --arg ns "${ns}" \
      '.items[] | select(.metadata.annotations["meta.helm.sh/release-name"]==$rel and .metadata.annotations["meta.helm.sh/release-namespace"]==$ns) | .metadata.name' 2>/dev/null || true)
  explicit_crds=""
  while read -r crd_name; do
    [[ -z "${crd_name}" ]] && continue
    explicit_crds="${explicit_crds}$(echo "${all_crds_json}" \
      | jq -r --arg name "${crd_name}" --arg rel "${release}" --arg ns "${ns}" \
        '.items[]
         | select(.metadata.name == $name)
         | select(
             ((.metadata.annotations["meta.helm.sh/release-name"] // "") == "")
             or
             (
               .metadata.annotations["meta.helm.sh/release-name"] == $rel
               and
               .metadata.annotations["meta.helm.sh/release-namespace"] == $ns
             )
           )
         | .metadata.name' 2>/dev/null || true)"$'\n'
  done < <(extra_crds_for_release "${release}")
  [[ -z "${manifest_crds}" && -z "${annotated_crds}" && -z "${explicit_crds}" ]] && return 0
  printf '%s\n%s\n%s\n' "${manifest_crds}" "${annotated_crds}" "${explicit_crds}" \
    | awk 'NF' \
    | sort -u \
    | while read -r crd_name; do
        check_crd_for_stuck_resources "${crd_name}" "${release}"
      done
  return 0
}

# ==============================================================================
# Pre-flight checks
# ==============================================================================
# Verify no custom resources with active finalizers exist for CRDs owned by
# bundle operators. After helm uninstall removes the operator, CRs with
# finalizers cannot be reconciled — blocking CRD deletion indefinitely.

if [[ "${SKIP_PREFLIGHT}" == "true" ]]; then
  echo "Skipping pre-flight checks (--skip-preflight)."
else
  echo "Running pre-flight checks..."
  PREFLIGHT_DETAILS=$(mktemp "${TMPDIR:-/tmp}/.aicr_preflight_XXXXXX")
  PREFLIGHT_ALL_CRDS_JSON=""

  if ! capture_kubectl_json PREFLIGHT_ALL_CRDS_JSON get crd -o json; then
    echo "" >&2
    echo "ERROR: Pre-flight could not list CRDs." >&2
    echo "  kubectl output: ${PREFLIGHT_ALL_CRDS_JSON}" >&2
    echo "  Failing closed: if this is a transient API/auth error the script" >&2
    echo "  may remove an operator before finalizers are reconciled." >&2
    echo "  Re-run after the API recovers, or use --skip-preflight to bypass." >&2
    rm -f "${PREFLIGHT_DETAILS}"
    exit 1
  fi
  if skip_preflight_for_release "nodewright-operator"; then
    echo "  Skipping nodewright-operator (skyhook): bundle deletes dependent manifests before controller uninstall."
  else
    echo "  Checking nodewright-operator (skyhook)..."
    check_release_for_stuck_crds "nodewright-operator" "skyhook"
  fi
  
  if [[ -s "${PREFLIGHT_DETAILS}" ]]; then
    echo ""
    echo "ERROR: Found custom resources with active finalizers that will block undeploy."
    echo "  After the operator is removed, these finalizers cannot be processed —"
    echo "  causing an unrecoverable hang during CRD deletion."
    echo ""
    echo "  Delete these resources while their controller is still running,"
    echo "  then re-run ./undeploy.sh"
    echo ""
    cat "${PREFLIGHT_DETAILS}"
    echo ""
    echo "  To skip this check: ./undeploy.sh --skip-preflight"
    rm -f "${PREFLIGHT_DETAILS}"
    exit 1
  fi
  rm -f "${PREFLIGHT_DETAILS}"

  echo "Pre-flight checks passed."
fi

# ==============================================================================
# Uninstall components in reverse install order
# ==============================================================================
# Generic reverse loop: every folder is a Helm release (local-helm or upstream-helm).
# `helm uninstall <release>` works uniformly for both kinds — that's one of the
# benefits of the uniform local-chart bundle format.
for dir in $(ls -1d "${SCRIPT_DIR}"/[0-9][0-9][0-9]-*/ 2>/dev/null | sort -r); do
  [[ -d "${dir}" ]] || continue
  base="${dir%/}"
  base="${base##*/}"
  name="${base#[0-9][0-9][0-9]-}"
  # Derive the namespace from the component name via the per-component blocks
  # below. We still need it for helm_force_uninstall and cluster-resource cleanup.
  ns=""
  if [[ "${name}" == "nodewright-operator" ]]; then ns="skyhook"; fi
  # Injected mixed-component "-post" folders share their parent's namespace.
  if [[ "${name}" == "nodewright-operator-post" ]]; then ns="skyhook"; fi
  if [[ -z "${ns}" ]]; then
    echo "Warning: no namespace known for ${name}; skipping uninstall" >&2
    continue
  fi
  echo "Uninstalling ${name} (${ns})..."
  # For local-helm folders (Chart.yaml + templates/), kubectl-delete the
  # rendered templates BEFORE helm uninstall. The templates may carry
  # helm.sh/hook annotations (post-install/post-upgrade) which helm does
  # not track or clean up on uninstall — so without this pre-delete, the
  # operator gets removed but its hook-created CRs (and their finalizers)
  # linger. Doing the delete while the controller is still running lets
  # finalizers clear naturally.
  if [[ -d "${dir}/templates" ]]; then
    for tpl in "${dir}/templates/"*.yaml; do
      [[ -f "${tpl}" ]] || continue
      kubectl delete -n "${ns}" -f "${tpl}" --ignore-not-found --timeout="${HELM_TIMEOUT}s" || true
    done
  fi
  helm_force_uninstall "${name}" "${ns}"
  delete_release_cluster_resources "${name}" "${ns}"
  delete_orphaned_webhooks_for_ns "${ns}"
done

# Remove nodewright node taints that persist after operator removal.
# Nodewright taints nodes during kernel tuning. The taint key is configurable
# via runtimeRequiredTaint (defaults to skyhook.nvidia.com).
NODEWRIGHT_TAINT_KEY="skyhook.nvidia.com"
# Locate nodewright-operator's NNN-prefixed directory at runtime.
nodewright_dir="$(ls -d "${SCRIPT_DIR}"/[0-9][0-9][0-9]-nodewright-operator 2>/dev/null | head -1)"
if [[ -n "${nodewright_dir}" && -f "${nodewright_dir}/values.yaml" ]]; then
  custom_taint_line=$(grep 'runtimeRequiredTaint:' "${nodewright_dir}/values.yaml" 2>/dev/null || true)
  if [[ -n "${custom_taint_line}" ]]; then
    # Extract value after "runtimeRequiredTaint:", then extract taint key before "="
    taint_value=$(echo "${custom_taint_line}" | sed 's/.*runtimeRequiredTaint:[[:space:]]*//' | tr -d '"' | tr -d "'")
    if [[ -n "${taint_value}" ]]; then
      # Handle both key=value:effect and key:effect formats
      NODEWRIGHT_TAINT_KEY="${taint_value%%=*}"
      NODEWRIGHT_TAINT_KEY="${NODEWRIGHT_TAINT_KEY%%:*}"
    fi
  fi
fi
echo "Removing ${NODEWRIGHT_TAINT_KEY} node taints..."
for node in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}' 2>/dev/null); do
  kubectl taint node "${node}" "${NODEWRIGHT_TAINT_KEY}-" 2>/dev/null || true
done

# Clean up orphaned CRDs that were owned by this bundle's releases.
# Only delete CRDs whose Helm release annotation matches a component we just uninstalled.
kubectl get crd -o json 2>/dev/null \
  | jq -r --arg rel "nodewright-operator" --arg ns "skyhook" \
    '.items[] | select(.metadata.annotations["meta.helm.sh/release-name"]==$rel and .metadata.annotations["meta.helm.sh/release-namespace"]==$ns) | .metadata.name' 2>/dev/null \
  | while read -r name; do
      echo "Deleting CRD ${name} (owned by nodewright-operator/skyhook)..."
      kubectl delete crd "${name}" --ignore-not-found --wait=false \
        || echo "Warning: failed to delete CRD ${name} (owned by nodewright-operator/skyhook); leftovers will surface in post-flight" >&2
    done || echo "Warning: orphan-CRD cleanup for nodewright-operator/skyhook failed (kubectl get / jq error); leftovers will surface in post-flight" >&2

# Intentionally skip automatic deletion of unannotated CRDs matched only by
# API group. On shared clusters, those CRDs may be serving another tenant's
# release in the same group, and we do not have bundle-specific ownership
# metadata to distinguish "ours" from "theirs" safely.

# Warn about CRDs stuck in deleting state (e.g., customresourcecleanup finalizer
# can't be resolved because CR instances still have controller-managed finalizers).
stuck_crds=$(kubectl get crd -o json 2>/dev/null | jq -r '.items[] | select(.metadata.deletionTimestamp != null) | .metadata.name' 2>/dev/null || true)
if [[ -n "${stuck_crds}" ]]; then
  echo ""
  echo "WARNING: CRDs stuck in deleting state:"
  for crd in ${stuck_crds}; do
    echo "  ${crd}"
  done
  echo ""
  echo "  These CRDs have a deletionTimestamp but cannot complete deletion because"
  echo "  their customresourcecleanup finalizer is waiting for CR instances to be"
  echo "  removed. If you are certain no data will be lost, you can force-clear the"
  echo "  finalizers. Note: this may leave orphaned CR data in etcd that is no longer"
  echo "  accessible through the API."
  echo ""
  echo "  Commands to force-clear (review before running):"
  for crd in ${stuck_crds}; do
    echo "    kubectl patch crd ${crd} --type merge -p '{\"metadata\":{\"finalizers\":null}}'"
  done
fi

# Clean up namespaces after all components are uninstalled.
if [[ "${DELETE_PVCS}" == "true" ]] && ! echo " ${PROTECTED_NS} " | grep -q " skyhook "; then
  echo "Deleting PVCs in skyhook..."
  kubectl delete pvc --all -n skyhook --ignore-not-found || true
fi
delete_orphaned_webhooks_for_ns "skyhook"
delete_namespace "skyhook"

# Clean up companion namespaces created at runtime by operators.
# Only emitted for components whose runtime creates them.

# Wait for terminating namespaces to finish
echo "Waiting for namespaces to terminate..."
for i in $(seq 1 60); do
  TERMINATING=$(kubectl get ns --no-headers 2>/dev/null | grep Terminating | awk '{print $1}' || true)
  if [[ -z "${TERMINATING}" ]]; then
    break
  fi
  if [[ $i -eq 60 ]]; then
    echo "Warning: namespaces still terminating after 60s: ${TERMINATING}"
    for ns in ${TERMINATING}; do
      force_clear_namespace_finalizers "${ns}"
      kubectl delete namespace "${ns}" --ignore-not-found --wait=false 2>/dev/null || true
    done
    break
  fi
  sleep 1
done

# Final webhook cleanup pass.
delete_orphaned_webhooks_for_ns "skyhook"

# ==============================================================================
# Post-flight verification
# ==============================================================================

postflight_issues=false

TERMINATING=""
postflight_ns_json=""
if capture_kubectl_json postflight_ns_json get namespaces -o json; then
  TERMINATING=$(echo "${postflight_ns_json}" \
    | jq -r '.items[] | select(.status.phase=="Terminating") | .metadata.name' 2>/dev/null \
    | tr '\n' ' ')
  TERMINATING="${TERMINATING% }"
else
  echo "Warning: failed to list namespaces for post-flight terminating check; kubectl output: ${postflight_ns_json}" >&2
  postflight_issues=true
fi
if [[ -n "${TERMINATING}" ]]; then
  echo "WARNING: namespaces still terminating: ${TERMINATING}"
  echo "  A subsequent deploy.sh may fail. Wait or force-finalize these namespaces."
  postflight_issues=true
fi

kubectl get mutatingwebhookconfigurations,validatingwebhookconfigurations -o json 2>/dev/null | \
  jq -r '.items[] | .metadata.name as $wh | .webhooks[]? | select(.clientConfig.service != null) | [$wh, .clientConfig.service.namespace, .clientConfig.service.name] | @tsv' 2>/dev/null | \
  sort -u | \
  while IFS=$'\t' read -r wh_name svc_ns svc_name; do
    if ! kubectl get ns "${svc_ns}" &>/dev/null || ! kubectl get svc "${svc_name}" -n "${svc_ns}" &>/dev/null; then
      echo "Deleting stale webhook ${wh_name} (service ${svc_ns}/${svc_name} missing)..."
      kubectl delete mutatingwebhookconfiguration "${wh_name}" --ignore-not-found 2>/dev/null || true
      kubectl delete validatingwebhookconfiguration "${wh_name}" --ignore-not-found 2>/dev/null || true
    fi
  done || true

stale_apis=$(kubectl get apiservices -o json 2>/dev/null | jq -r '.items[] | select(.status.conditions[]? | .type == "Available" and .status == "False") | .metadata.name' 2>/dev/null || true)
if [[ -n "${stale_apis}" ]]; then
  echo "WARNING: unavailable API services found: ${stale_apis}"
  echo "  These can block namespace deletion. Delete with: kubectl delete apiservice <name>"
  postflight_issues=true
fi

# Check for Helm-annotated CRDs from uninstalled releases.
helm_orphaned_crds=""
explicit_orphaned_crds=""
postflight_all_crds_json=""
if capture_kubectl_json postflight_all_crds_json get crd -o json; then
  :
  remaining_helm_crds=$(echo "${postflight_all_crds_json}" \
    | jq -r --arg rel "nodewright-operator" --arg ns "skyhook" \
      '.items[] | select(.metadata.annotations["meta.helm.sh/release-name"]==$rel and .metadata.annotations["meta.helm.sh/release-namespace"]==$ns and .metadata.deletionTimestamp==null) | .metadata.name' 2>/dev/null || true)
  if [[ -n "${remaining_helm_crds}" ]]; then
    helm_orphaned_crds="${helm_orphaned_crds} ${remaining_helm_crds}"
  fi
  while read -r crd_name; do
    [[ -z "${crd_name}" ]] && continue
    remaining_explicit_crd=$(echo "${postflight_all_crds_json}" \
      | jq -r --arg name "${crd_name}" \
        '.items[] | select(.metadata.name==$name and .metadata.deletionTimestamp==null) | .metadata.name' 2>/dev/null || true)
    if [[ -n "${remaining_explicit_crd}" ]]; then
      explicit_orphaned_crds="${explicit_orphaned_crds}${remaining_explicit_crd}"$'\n'
    fi
  done < <(extra_crds_for_release "nodewright-operator")
else
  echo "Warning: failed to enumerate post-flight CRDs; kubectl output: ${postflight_all_crds_json}" >&2
  postflight_issues=true
fi
if [[ -n "${helm_orphaned_crds}" ]]; then
  echo "WARNING: Helm-annotated CRDs from uninstalled releases still present:${helm_orphaned_crds}"
  echo "  Cleanup did not remove all CRDs owned by this bundle's releases."
  echo "  Delete with: kubectl delete crd <name>"
  postflight_issues=true
fi

explicit_orphaned_crds=$(printf '%s' "${explicit_orphaned_crds}" | awk 'NF' | sort -u | tr '\n' ' ')
if [[ -n "${explicit_orphaned_crds}" ]]; then
  echo "WARNING: explicit CRDs from this bundle still present: ${explicit_orphaned_crds}"
  echo "  These CRDs are installed outside Helm manifest/annotation discovery."
  echo "  Delete with: kubectl delete crd <name>"
  postflight_issues=true
fi

if [[ "${postflight_issues}" == "true" ]]; then
  echo ""
  echo "Post-flight: some stale resources remain. Run deploy.sh pre-flight checks to verify before redeploying."
else
  echo "Post-flight: cluster is clean."
fi

echo "Undeployment complete."
